name: Publish Python Package to PyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: 'v1.17.1'


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: "Download binaries from ${{ github.event.inputs.tag }}"
        uses: robinraju/release-downloader@v1.9
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.inputs.tag }}
          fileName: "*"
          out-file-path: "dist"

      - name: Test
        run: |
          ls dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}